platform :ios, '14.0'
use_frameworks!

target 'iosApp' do
  pod 'Google-Mobile-Ads-SDK'
  pod 'FBAudienceNetwork'
  pod 'AppLovinSDK'
  pod 'InMobiSDK'
  pod 'VungleAds'
  pod 'Ads-Global'
  pod 'IronSourceSDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete('EXCLUDED_ARCHS')
      config.build_settings.delete('EXCLUDED_ARCHS[sdk=iphonesimulator*]')
    end
  end
end
